version: '3.8'

services:
  localstack:
    container_name: your-service-localstack
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      # Core configuration
      - SERVICES=s3,dynamodb,sqs,secretsmanager,lambda,apigateway,cloudwatch,logs
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock

      # AWS configuration
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

      # LocalStack specific
      - LOCALSTACK_HOST=localhost.localstack.cloud:4566
      - HOSTNAME_EXTERNAL=localhost
      - EDGE_PORT=4566

      # Feature flags
      - SKIP_SSL_CERT_DOWNLOAD=1
      - DISABLE_EVENTS=1

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - your-service-network

networks:
  your-service-network:
    driver: bridge

volumes:
  localstack-data:
    driver: local